probit methods
Circlegain/exmods pull request #12
Opened 2020-11-03 08:40 UTC by eanea

closes #6

2020-11-03 09:19 UTC, catena2w approved these changes

2020-11-03 09:50 UTC, oskin1 requested changes

2020-11-03 09:50 UTC, oskin1 commented on probit/src/main/scala/com/circlegain/exmods/probit/Probit.scala
> +    Raise[F, NotSupported].raise(NotSupported("transactionsHistory"))
Please use syntax `tofu.syntax.raise._`

2020-11-03 09:50 UTC, oskin1 commented on probit/src/main/scala/com/circlegain/exmods/probit/internal/models/Trade.scala
> +    O: Make[OrderSide, domain.OrderType, F]
Lets use more meaningful names for custom modules such as Make. 
```suggestion
    makeOrderType: Make[OrderSide, domain.OrderType, F]
```

2020-11-03 17:31 UTC, oskin1 commented on probit/src/main/scala/com/circlegain/exmods/probit/internal/models/OrderSide.scala
> +  implicit def makeDomain[F[_]: Monad: Clock: Raise[*[_], MalformedResponse]]: Make[OrderSide, domain.OrderType, F] =
Seems these constraints are redundant here `F[_]: Monad: Clock: Raise[*[_], MalformedResponse]`

2020-11-03 17:32 UTC, oskin1 commented on probit/src/main/scala/com/circlegain/exmods/probit/internal/models/OrderSide.scala
> +      case Buy  => widen(domain.Bid).pure
Consider upcasting via Scala syntax `domain.Bid: OrderType`

2020-11-03 17:33 UTC, eanea commented on probit/src/main/scala/com/circlegain/exmods/probit/Probit.scala
> +    Raise[F, NotSupported].raise(NotSupported("transactionsHistory"))
:+1:

2020-11-03 17:34 UTC, oskin1 commented on probit/src/main/scala/com/circlegain/exmods/probit/internal/models/Trade.scala
> +  implicit def makeDomain[F[_]: Monad: Clock: Raise[*[_], MalformedResponse]](implicit
Are all these constraints used?

2020-11-03 17:54 UTC, eanea commented on probit/src/main/scala/com/circlegain/exmods/probit/internal/models/Trade.scala
> +  implicit def makeDomain[F[_]: Monad: Clock: Raise[*[_], MalformedResponse]](implicit
fixed

2020-11-04 09:12 UTC, oskin1 commented on probit/src/main/scala/com/circlegain/exmods/probit/internal/models/OrderSide.scala
> +  }
Use [https://github.com/lloydmeta/enumeratum](url) in order to avoid writing discriminating codecs by hand.

2020-11-04 09:13 UTC, oskin1 approved these changes

2020-11-04 15:49 UTC, eanea commented on probit/src/main/scala/com/circlegain/exmods/probit/internal/models/OrderSide.scala
> +  }
:+1:

2020-11-04 15:57 UTC, merged