Binance methods
Circlegain/exmods pull request #4
Opened 2020-11-02 10:25 UTC by eanea

2020-11-02 10:41 UTC, catena2w commented
close #5

2020-11-02 10:41 UTC, catena2w requested changes
Please extract common test code to a separate package. See https://github.com/Circlegain/exmods/issues/7

2020-11-02 10:43 UTC, catena2w commented on binance/src/main/scala/com/circlegain/exmods/binance/Binance.scala
> +      depositHistory <- client
As far as we anyway make 2 independent requests here, let's implement 2 methods `depositHistory` and `withdrawHistory` and combine them together in this interface method

2020-11-02 10:45 UTC, catena2w commented on binance/src/test/scala/BinanceSpec.scala
> +    println("probit")
Pleases remove println and add rule to forbid it. 
Also  - why is it called probit here?

2020-11-02 15:12 UTC, oskin1 commented on binance/src/main/scala/com/circlegain/exmods/binance/internal/models/BinanceTradeHistoryParams.scala
> +                   historyParams.setEndTime(paging.endTime.map(l => new Date(l)).orNull)
Effectful statements shouldn't appear inside map

2020-11-02 22:14 UTC, oskin1 commented on binance/src/main/scala/com/circlegain/exmods/binance/internal/models/BinanceTradeHistoryParams.scala
> +      curPair <- pairOp.map(_.make[F, CurrencyPair]).sequence
```suggestion
      curPair <- pairOp.traverse(_.make[F, CurrencyPair])
```

2020-11-03 09:14 UTC, eanea commented on binance/src/main/scala/com/circlegain/exmods/binance/Binance.scala
> +      depositHistory <- client
done

2020-11-03 09:15 UTC, eanea commented on binance/src/main/scala/com/circlegain/exmods/binance/internal/models/BinanceTradeHistoryParams.scala
> +                   historyParams.setEndTime(paging.endTime.map(l => new Date(l)).orNull)
done

2020-11-03 09:15 UTC, eanea commented on binance/src/main/scala/com/circlegain/exmods/binance/internal/models/BinanceTradeHistoryParams.scala
> +      curPair <- pairOp.map(_.make[F, CurrencyPair]).sequence
:+1:

2020-11-03 09:15 UTC, eanea commented on binance/src/test/scala/BinanceSpec.scala
> +    println("probit")
dropped

2020-11-03 09:18 UTC, catena2w approved these changes

2020-11-03 09:43 UTC, oskin1 requested changes

2020-11-03 09:43 UTC, oskin1 commented on binance/src/main/scala/com/circlegain/exmods/binance/Binance.scala
> +    params        <- BinanceTradeHistoryParams[F](pair, paging)
Explicit type annotation is redundant here

2020-11-03 09:43 UTC, oskin1 commented on binance/src/main/scala/com/circlegain/exmods/binance/Binance.scala
> +    tradesHistory <- client.tradesHistory(params.orNull).flatMap(_.traverse(_.make[F, Trade]))
Are you seriously passing `null` to Scala method? Please make `client.tradesHistory` accepting optional value.

2020-11-03 09:43 UTC, oskin1 commented on binance/src/main/scala/com/circlegain/exmods/binance/internal/models/BinanceTradeHistoryParams.scala
> +    } yield params
```suggestion
  def apply[F[_]: Sync](tokenPair: TokenPair, paging: Paging): F[service.BinanceTradeHistoryParams] =
    for {
      curPair <- tokenPair.make[F, CurrencyPair]
      params = new service.BinanceTradeHistoryParams(curPair)
      _ <- Sync[F].delay(params.setStartTime(paging.startTime.map(l => new Date(l)).orNull))
      _ <- Sync[F].delay(params.setEndTime(paging.endTime.map(l => new Date(l)).orNull))
      _ <- Sync[F].delay(params.setLimit(paging.limit.map(int2Integer).orNull))
    } yield params
```

2020-11-03 09:43 UTC, oskin1 commented on binance/src/main/scala/com/circlegain/exmods/binance/internal/models/BinanceTradeHistoryParams.scala
> +  def apply[F[_]: Sync](pairOp: Option[TokenPair], paging: Paging): F[Option[service.BinanceTradeHistoryParams]] =
You are passing optional argument to a method whose output completely depends on it. It's pointless, optionality of the `pairOp` arg should be processed at the call level.

2020-11-03 18:18 UTC, eanea commented on binance/src/main/scala/com/circlegain/exmods/binance/Binance.scala
> +    tradesHistory <- client.tradesHistory(params.orNull).flatMap(_.traverse(_.make[F, Trade]))
:confused:

2020-11-03 18:18 UTC, eanea commented on binance/src/main/scala/com/circlegain/exmods/binance/internal/models/BinanceTradeHistoryParams.scala
> +  def apply[F[_]: Sync](pairOp: Option[TokenPair], paging: Paging): F[Option[service.BinanceTradeHistoryParams]] =
:+1:

2020-11-04 07:00 UTC, oskin1 commented on binance/src/main/scala/com/circlegain/exmods/binance/Binance.scala
> +  def make[I[+_]: Sync, F[+_]: Sync: Clock](
Why declaring F as covariant?

2020-11-04 07:39 UTC, eanea commented on binance/src/main/scala/com/circlegain/exmods/binance/Binance.scala
> +  def make[I[+_]: Sync, F[+_]: Sync: Clock](
it's used to work around inference of OrderType

2020-11-04 15:55 UTC, oskin1 commented on binance/src/main/scala/com/circlegain/exmods/binance/internal/instances.scala
> +    orderTypeM: Make[dto.Order.OrderType, OrderType, F],
Why requiring these implicit makes?
You can just auto summon them in place using syntax.

2020-11-04 16:00 UTC, eanea commented on binance/src/main/scala/com/circlegain/exmods/binance/internal/instances.scala
> +    orderTypeM: Make[dto.Order.OrderType, OrderType, F],
:+1:

2020-11-04 16:31 UTC, oskin1 approved these changes

2020-11-04 18:25 UTC, merged